%%
%% This is file `elegantnote.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% elegantlatex.dtx  (with options: `note')
%% ----------------------------------------------------------------
%% ElegantLaTeX --- Elegant and Beautiful LaTeX templates.
%% Author: Ethan Deng and Liam Huang
%% Source: https://github.com/ElegantLaTeX
%% E-mail: elegantlatex2e@gmail.com
%% Released under the LaTeX Project Public License v1.3c or later
%% See http://www.latex-project.org/lppl.txt
%% ----------------------------------------------------------------
%% 

\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{elegantnote}[2020/08/26 v1.0 Elegant Note Template]

\begin{macro}{\examplemacro}
  \changes{v1.0}{2009/10/06}{Some change from the previous version}
  \newcommand*\examplemacro[2][]{%
    Some code here, probably
}
\end{macro}
%% 
%% Copyright (C) 2009 by ElegantLaTeX <elegantlatex2e@gmail.com>
%% 
%% This work may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License (LPPL), either
%% version 1.3c of this license or (at your option) any later
%% version.  The latest version of this license is in the file:
%% 
%% http://www.latex-project.org/lppl.txt
%% 
%% This work is "maintained" (as per LPPL maintenance status) by
%% You.
%% 
%% This work consists of the file  elegantlatex.dtx
%% and the derived files           elegantlatex.ins,
%%                                 elegantlatex.pdf,
%%                                 elegantnote.cls,
%%                                 elegantbook.cls and
%%                                 elegantpaper.cls.
%% 
%%
%% End of file `elegantnote.cls'.
